### ISSUE TITLE
Research: decide source of recipes

### ISSUE THREAD

**Issue by hannahhui5184** [cse110-fa21-group32/cse110-fa21-group32#16]
- Research ways to get recipes (JSON-LD, API)
- Record brief tutorial notes and put a demo into the `/prototype` folder
- Present best source of recipes with suggestions of where to store & load them into the pages

**Comment by hannahhui5184** [comment]
Update:
- APIs: came across a lot of paid APIs, check out https://spoonacular.com/food-api again
- talked with the TA, expectation that we populate with 100s of recipes

**Comment by StuartBoynton1** [comment]
Update:

 - We have decided to use the spoonacular API 
 - This will allow us to search for recipes in its database 
 - It also allows us to retrieve full JSON files for its recipes
 - Possibly will be able to provide other functionality
